#!/usr/bin/env python3

import os
import re
import sys
import portage
import subprocess


class Util:

    @staticmethod
    def die(message):
        print(message, file=sys.stderr)
        sys.exit(1)

    @classmethod
    def getFileList(cls, dirName, level, typeList):
        """typeList is a string, value range is "d,f,l,a"
           returns basename"""

        ret = []
        for fbasename in os.listdir(dirName):
            fname = os.path.join(dirName, fbasename)

            if os.path.isdir(fname) and level - 1 > 0:
                for i in cls.getFileList(fname, level - 1, typeList):
                    ret.append(os.path.join(fbasename, i))
                continue

            appended = False
            if not appended and ("a" in typeList or "d" in typeList) and os.path.isdir(fname):         # directory
                ret.append(fbasename)
            if not appended and ("a" in typeList or "f" in typeList) and os.path.isfile(fname):        # file
                ret.append(fbasename)
            if not appended and ("a" in typeList or "l" in typeList) and os.path.islink(fname):        # soft-link
                ret.append(fbasename)

        return ret

    @staticmethod
    def repoIsSysFile(fbasename):
        """fbasename value is like "sys-devel", "sys-devel/gcc", "profiles", etc"""

        if fbasename.startswith("."):
            return True
        if fbasename == "licenses" or fbasename.startswith("licenses/"):
            return True
        if fbasename == "metadata" or fbasename.startswith("metadata/"):
            return True
        if fbasename == "profiles" or fbasename.startswith("profiles/"):
            return True
        if fbasename == "eclass" or fbasename.startswith("eclass/"):
            return True
        return False

    @classmethod
    def portageGetInstalledPkgAtomList(cls, portageDbDir):
        pkgAtomList = []
        for fbasename in sorted(cls.getFileList(portageDbDir, 2, "d")):
            if cls.repoIsSysFile(fbasename):
                continue
            if fbasename.split("/")[1].startswith("-MERGING"):
                continue
            pkgAtomList.append(fbasename)
        return pkgAtomList

    @staticmethod
    def portagePkgNameVerToPkgName(pkgNameVer):
        parts = pkgNameVer.split('-')
        while len(parts) > 1:
            # FIXME: should call portage to do this
            bMatch = False
            if not bMatch and re.fullmatch(r"^r?[0-9\.]+([A-Za-z_]+)?", parts[-1]):
                bMatch = True
            if not bMatch and re.fullmatch(r"^[0-9\.]+(_pre|_p|_alpha|_beta|_rc)[0-9]+", parts[-1]):
                bMatch = True
            if not bMatch:
                break
            parts = parts[:-1]
        return "-".join(parts)

    @staticmethod
    def portageGetPkgAllUseFlags(pkgAtom):
        vartree = portage.db[portage.root]["vartree"]
        cpv_list = vartree.dbapi.match(pkgAtom)
        latest_cpv = cpv_list[0]
        ret = vartree.dbapi.aux_get(latest_cpv, ["IUSE"])[0].split()
        return [x.replace("+", "") for x in ret]


def getCurrentPythonVersion():
    out = subprocess.check_output(["python", "--version"], text=True)
    m = re.search("Python ([0-9]+.[0-9]+).[0-9]+", out)
    return m.group(1)


def getPythonVersionList():
    fullfn = "/etc/python-exec/python-exec.conf"
    ret = []
    with open(fullfn) as f:
        for line in f:
            line = line.strip()
            if line == "" or line.startswith("#"):
                continue
            m = re.search(r"^python([0-9]+\.[0-9]+)", line)
            ret.append(m.group(1))
    return sorted(ret)


def checkAndPrint(ver):
    portageDbDir = "/var/db/pkg"
    prefixUse = "python_targets_"
    prefixSingleUse = "python_single_target_"
    defaultUse = "python_targets_python%s" % (ver.replace(".", "_"))
    defaultSingleUse = "python_single_target_python%s" % (ver.replace(".", "_"))

    ret = []
    for pkgNameVer in sorted(Util.portageGetInstalledPkgAtomList(portageDbDir)):
        pkgName = Util.portagePkgNameVerToPkgName(pkgNameVer)
        useList = Util.portageGetPkgAllUseFlags(pkgName)
        if any(x.startswith(prefixUse) for x in useList) and defaultUse not in useList:
            ret.append("Package \"%s\" has no USE flag \"%s\"." % (pkgName, defaultUse))
        if any(x.startswith(prefixSingleUse) for x in useList) and defaultSingleUse not in useList:
            ret.append("Package \"%s\" has no USE flag \"%s\"." % (pkgName, defaultSingleUse))

    if len(ret) > 0:
        print("Python %s:" % (ver))
        for x in ret:
            print("    " + x)

    return len(ret) > 0


if __name__ == '__main__':
    if len(sys.argv) > 1:
        if sys.argv[1] == "--check":
            curVer = getCurrentPythonVersion()
            bFound = False
            bStart = False
            for v in getPythonVersionList():
                if not bStart and v == curVer:
                    bStart = True
                if bStart:
                    bFound |= checkAndPrint(v)
            if not bStart:
                bFound |= checkAndPrint(curVer)
            sys.exit(0 if not bFound else 1)
        else:
            ret = subprocess.run(["python-exec2c", "python3-config"] + sys.argv[1:])
            sys.exit(ret.returncode)
    else:
        ret = subprocess.run(["python-exec2c", "python3-config"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        assert ret.returncode == 1
        assert ret.stdout == ""
        assert ret.stderr.startswith("Usage:")
        sys.stderr.write(re.sub(r"(\|.*)$", r"\1|--check", ret.stderr, flags=re.M))
        sys.exit(ret.returncode)
