#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import re
import sys
import portage_cfg
from gstage4._patcher import RepoPatcher


def get_int_or_none(s):
    if s is None:
        return None
    try:
        return int(s)
    except ValueError:
        return None


def usage():
    print("Usage:")
    print("  %s <repository name> <sync uri> <location>" % (sys.argv[0]))


if __name__ == "__main__":
    if len(sys.argv) == 2 and sys.argv[1] == "--help":
        usage()
        sys.exit(0)

    if len(sys.argv) < 4:
        usage()
        sys.exit(1)

    sourceDir = sys.argv[0] + ".d"
    targetDirRepoName = sys.argv[1]
    syncUrl = sys.argv[2]                   # not used, only to fulfill gentoo postsync.d script spec
    targetDir = sys.argv[3]

    jobNumber = None
    loadAverage = None
    if True:
        makeConf = portage_cfg.MakeConf()
        if jobNumber is None or loadAverage is None:
            value = makeConf.get_var("MAKEOPTS")
            if jobNumber is None:
                m = re.search("\\B--jobs(=([0-9]+))?\\b", value)
                if m is not None:
                    jobNumber = get_int_or_none(m.group(2))
            if jobNumber is None:
                m = re.search("\\B-j([0-9]+)?\\b", value)
                if m is not None:
                    jobNumber = get_int_or_none(m.group(1))
            if loadAverage is None:
                m = re.search("\\B--load-average(=([0-9\\.]+))?\\b", value)
                if m is not None:
                    loadAverage = get_int_or_none(m.group(2))
            if loadAverage is None:
                m = re.search("\\B-l([0-9]+)?\\b", value)
                if m is not None:
                    loadAverage = get_int_or_none(m.group(1))
        if jobNumber is None or loadAverage is None:
            value = makeConf.get_var("EMERGE_DEFAULT_OPTS")
            if jobNumber is None:
                m = re.search("\\B--jobs(=([0-9]+))?\\b", value)
                if m is not None:
                    jobNumber = get_int_or_none(m.group(2))
            if loadAverage is None:
                m = re.search("\\B--load-average(=([0-9\\.]+))?\\b", value)
                if m is not None:
                    loadAverage = get_int_or_none(m.group(2))
    if jobNumber is None:
        jobNumber = 1

    patcher = RepoPatcher(jobNumber=jobNumber, loadAverage=loadAverage)
    patchDirList = [os.path.join(sourceDir, x) for x in os.listdir(sourceDir)]
    patchDirList = patcher.filter_patch_dir_list(patchDirList, targetDirRepoName)
    if len(patchDirList) > 0:
        print("Patching...")
        pendingDstDirSet = patcher.patch(targetDir, patchDirList, targetDirRepoName)
        for x in patcher.warn_or_err_list:
            if x.warn_or_err:
                print("Warning: %s" % (x.msg))
            else:
                print("Error: %s" % (x.msg), file=sys.stderr)
        if any([not x.warn_or_err for x in patcher.warn_or_err_list]):
            sys.exit(1)
        patcher.generateManifest(pendingDstDirSet)
        print("Done.")
