#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import json
import pathlib
import subprocess


def openCodeCall(workDir, prompt, logfile=None):
    env = os.environ.copy()
    env["OPENCODE_PERMISSION"] = '{"*": "allow"}'

    prompt = "You take the most appropriate action and output the result, there's no chance to interact with the user.\n\n" + prompt

    ret = subprocess.check_output(["opencode", "run", "--model", "opencode/big-pickle", "--dir", workDir, "--format", "json", prompt],
                                    stderr=subprocess.STDOUT, text=True, env=env)

    if logfile is not None:
        pathlib.Path(logfile).write_text(ret)

    ret = ret.rstrip("\n").split("\n")[-2]      # the last output is "step_finish", the second to last output is the result
    ret = json.loads(ret)
    ret = ret["part"]["text"]
    ret = json.loads(ret)

    return ret


if __name__ == "__main__":
    if not os.path.exists("/usr/bin/opencode"):
        print("Error: opencode (dev-util/opencode-bin) is not installed.", file=sys.stderr)
        sys.exit(1)

    selfDir = os.path.dirname(os.path.realpath(__file__))

    projectFullDir = os.path.normpath(os.path.join(selfDir, ".."))

    patchRepoDir = os.path.join("libexec", "patch-repository.d")
    patchRepoFullDir = os.path.join(projectFullDir, patchRepoDir)

    cacheFullDir = os.path.join(selfDir, "cache")
    os.makedirs(cacheFullDir, exist_ok=True)

    prompt = f"""
You are helping maintain {patchRepoDir} in this project.

Project Directory: {projectFullDir}

Actions:
- Comply to AGENTS.md in the project.
- Check every directory and file in patch-repository.d to identify outdated content.
- Don't run any thing, just read, anaylse, edit file
- Fix any outdated content you find.
- If a file or directory is no longer needed (e.g., the bug was fixed upstream), remove it.
- Don't commit, I'll check the result.
- Report what was fixed and what files remain outdated in the end.

You should download / update the related gentoo repository / overlay into cahe directory and analyse them with project coden together.
Cache directory may already contains data from last run.

Cache Directory: {cacheFullDir}
"""

    ret = openCodeCall(projectFullDir, prompt, logfile=os.path.ojin(cacheFullDir, "opencode.log"))
    print(ret)
 